services:
  mc:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "true"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGE_VERSION: "14.23.5.2860"
      PACKWIZ_URL: "https://raw.githubusercontent.com/HydratedBean/Project-Virulence/refs/heads/main/pack.toml"
      LEVEL_TYPE: BIOMESOP
      DIFFICULTY: normal
      WHITELIST: |
      OPS: |
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
